FROM kong/kong-gateway:latest

# Copy the Kong configuration file
COPY /kong/kong.yaml /etc/kong/kong.yml

# Set environment variables for DB-less mode
ENV KONG_DATABASE=off
ENV KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
ENV KONG_PROXY_ACCESS_LOG=/dev/stdout
ENV KONG_ADMIN_ACCESS_LOG=/dev/stdout
ENV KONG_PROXY_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_ERROR_LOG=/dev/stderr
ENV KONG_ADMIN_LISTEN=0.0.0.0:8001

# Expose necessary ports
EXPOSE 8000 8001 8443 8444

# Start Kong
CMD [ "kong", "docker-start" ]
